name: nlt_bible
description: A future-based dart package for the NLT API from Tyndale House Publishers which can be used to fetch NLT bible passages.
version: 0.0.1
homepage: https://github.com/arielmagbanua/nlt_bible

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  html: ^0.15.0

dev_dependencies:
  test: ^1.21.4
  mocktail: ^0.3.0
  lint: ^1.10.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
